Skip to content
Native
Repository navigation
Code
Issues
Actions
Build APK — LOTATO PRO
Create main.yml #1
Annotations
1 error and 1 warning
Build APK Android
failed 19 minutes ago in 12s
3s
0s
1s
4s
Run actions/setup-node@v4
Attempting to download 20...
Acquiring 20.20.2 - x64 from https://github.com/actions/node-versions/releases/download/20.20.2-23521894959/node-20.20.2-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/df7124cd-1a12-4b77-a719-f14e96e61eaa -f /home/runner/work/_temp/a02bb216-de19-4a56-bb24-f63fd7b2ca16
Adding to the cache ...
Environment details
/opt/hostedtoolcache/node/20.20.2/x64/bin/npm config get cache
/home/runner/.npm
Error: Dependencies lock file is not found in /home/runner/work/Native/Native. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
0s
1s
0s
